name = "misty-term-0063"
main = "src/index.js"
compatibility_date = "2023-10-25"

route = { pattern = "misty-term-0063.henoch-hernanda.workers.dev", custom_domain = true }

[site]
bucket = "./public"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "recipe-store"
database_id = "b2109422-c687-4ee4-989a-cf429b34733b"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "vector-index"

